# Generated by Django 4.0.3 on 2022-04-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=300)),
                ('title', models.TextField(max_length=600)),
                ('description', models.TextField(max_length=1000)),
                ('button', models.TextField(max_length=300)),
                ('button_link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Home Title',
                'verbose_name_plural': 'Home Title',
            },
        ),
    ]
