# Generated by Django 4.0.3 on 2022-04-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hometitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTitle2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=300)),
                ('title', models.TextField(max_length=600)),
                ('description', models.TextField(max_length=1000)),
                ('button', models.TextField(max_length=300)),
                ('button_link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Home Title 2',
                'verbose_name_plural': 'Home Title 2',
            },
        ),
        migrations.RenameModel(
            old_name='HomeTitle',
            new_name='HomeTitle1',
        ),
        migrations.AlterModelOptions(
            name='hometitle1',
            options={'verbose_name': 'Home Title 1', 'verbose_name_plural': 'Home Title 1'},
        ),
    ]
