# Generated by Django 4.0.3 on 2022-04-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_hometitle1_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometitle1',
            name='content',
        ),
        migrations.AddField(
            model_name='hometitle1',
            name='description1',
            field=models.TextField(default='title1', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometitle1',
            name='description2',
            field=models.TextField(default='title2', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometitle1',
            name='title1',
            field=models.CharField(default='desc1', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometitle1',
            name='title2',
            field=models.CharField(default='decs2', max_length=300),
            preserve_default=False,
        ),
    ]
