# Generated by Django 4.0.3 on 2022-04-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_featuredimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredimages',
            options={'verbose_name': 'Feaured Images', 'verbose_name_plural': 'Feaured Images'},
        ),
    ]
