# Generated by Django 4.0.3 on 2022-04-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_featuredimages_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedImages',
        ),
    ]
