# Generated by Django 4.0.3 on 2022-04-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_featuredimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='video/', verbose_name='Background Video')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('button', models.TextField(max_length=300)),
                ('button_link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Home Title',
                'verbose_name_plural': 'Home Title',
            },
        ),
        migrations.DeleteModel(
            name='HomeTitle1',
        ),
        migrations.DeleteModel(
            name='HomeTitle2',
        ),
    ]
