# Generated by Django 4.0.3 on 2022-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_hometitle_delete_hometitle1_delete_hometitle2'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometitle',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/logo/', verbose_name='Logo image'),
        ),
    ]
