# Generated by Django 4.0.3 on 2022-04-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_hometitle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometitle',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
