# Generated by Django 4.0.3 on 2022-04-17 05:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_hometitle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeaboutsection',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
