# Generated by Django 4.0.3 on 2022-04-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrendProduct',
        ),
    ]
